### ISSUE TITLE
MD_MAX72xx starts causing issues when WiiClassicController is included into the project (????)

### ISSUE THREAD

**Issue by joveaaron** [AndrewMascolo/WiiClassicController#2]
I don't know why this is happening. All I wanted is to control this Tetris game with my NES Classic Mini Controller (tested working on example project file)  but I simply can't. Can anyone help me out with this?? 

Video:
https://www.youtube.com/watch?v=ZnHVAxcUmak

**Comment by joveaaron** [comment]
Also when I press the Up arrow, the Left arrow triggers aswell. Any ideas why?

**Comment by AndrewMascolo** [comment]
Is it only the combination for the WiiClassicController and MD_MAXPanel libraries? 
Do both libraries work by themselves?
What happens if you comment out MD_MAXPanel.h or one of the other libraries you are using?

As for the Up and Left arrow buttons, it could be a defect with the controller. The WiiClassicController library has a debug feature that allows you to test each button.

**Comment by joveaaron** [comment]
@AndrewMascolo 
Yes. But I tried on only WiiClassicController and MD_MAX72xx and it was giving the same problems.

[MD_MAXPanel.txt](https://github.com/AndrewMascolo/WiiClassicController/files/6736250/MD_MAXPanel.txt)
(renamed so GitHub accepts this file type)

**Comment by joveaaron** [comment]
@AndrewMascolo 

I have another (fake) NES controller that works so I can use that one. And leave my OG one to my NES Classic.

**Comment by AndrewMascolo** [comment]
Would you be able to upload all your files and libraries being used this way I can recreate the issue on my end?

**Comment by joveaaron** [comment]
I cant nr I can tomorrow.

**Comment by joveaaron** [comment]
yo wtf

just tried to put the #include for the library below the md_max panel thing and it works?
I need further testing. I will include files when an error occurs.

Thank you for your help

**Comment by joveaaron** [comment]
Thank you! But it was just that it was freaking out because the WiiClassicController library was the first. I placed it at the end of the #includes and it worked.
